version: '2'
services:
  app:
    image: nodebb/docker:latest
    ports:
      - "4567:4567"
    volumes:
      - .:/code
    working_dir: /code
    command: node app.js
    links:
      - mongodb
    environment:
      NODE_ENV: production
      daemon: 0
      silent: 0
    restart: always

  mongodb:
    image: mongo:3.2.3
    volumes:
      - ./tmp/database/mongodb:/data/db
    ports:
      - "27017:27017"
    restart: always